// Mocks generated by Mockito 5.0.13 from annotations
// in newsapi_flutter/test/unit_tests/repositories/articles_repository_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:newsapi_flutter/src/model/data_sources/articles_remote_data_source.dart'
    as _i3;
import 'package:newsapi_flutter/src/model/models/articles_response.dart' as _i2;
import 'package:newsapi_flutter/src/model/models/everything_param.dart' as _i6;
import 'package:newsapi_flutter/src/model/models/headlines_param.dart' as _i5;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeArticlesResponse extends _i1.Fake implements _i2.ArticlesResponse {}

/// A class which mocks [ArticlesRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockArticlesRemoteDataSource extends _i1.Mock
    implements _i3.ArticlesRemoteDataSource {
  MockArticlesRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ArticlesResponse> fetchHeadlines(
          _i5.HeadLinesParams? params) =>
      (super.noSuchMethod(Invocation.method(#fetchHeadlines, [params]),
              returnValue:
                  Future<_i2.ArticlesResponse>.value(_FakeArticlesResponse()))
          as _i4.Future<_i2.ArticlesResponse>);
  @override
  _i4.Future<_i2.ArticlesResponse> fetchEverything(
          _i6.EveryThingParams? params) =>
      (super.noSuchMethod(Invocation.method(#fetchEverything, [params]),
              returnValue:
                  Future<_i2.ArticlesResponse>.value(_FakeArticlesResponse()))
          as _i4.Future<_i2.ArticlesResponse>);
  @override
  String toString() => super.toString();
}
