// Mocks generated by Mockito 5.0.13 from annotations
// in newsapi_flutter/test/unit_tests/usecases/get_everything_articles_usecase_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:newsapi_flutter/src/core/error/failures.dart' as _i5;
import 'package:newsapi_flutter/src/model/models/article.dart' as _i6;
import 'package:newsapi_flutter/src/model/models/everything_param.dart' as _i8;
import 'package:newsapi_flutter/src/model/models/headlines_param.dart' as _i7;
import 'package:newsapi_flutter/src/model/repository/articles_repository.dart'
    as _i3;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeEither<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [ArticlesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockArticlesRepository extends _i1.Mock
    implements _i3.ArticlesRepository {
  MockArticlesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Article>>> getTopHeadlines(
          _i7.HeadLinesParams? params) =>
      (super.noSuchMethod(Invocation.method(#getTopHeadlines, [params]),
          returnValue: Future<_i2.Either<_i5.Failure, List<_i6.Article>>>.value(
              _FakeEither<_i5.Failure, List<_i6.Article>>())) as _i4
          .Future<_i2.Either<_i5.Failure, List<_i6.Article>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Article>>> getEverything(
          _i8.EveryThingParams? params) =>
      (super.noSuchMethod(Invocation.method(#getEverything, [params]),
          returnValue: Future<_i2.Either<_i5.Failure, List<_i6.Article>>>.value(
              _FakeEither<_i5.Failure, List<_i6.Article>>())) as _i4
          .Future<_i2.Either<_i5.Failure, List<_i6.Article>>>);
  @override
  String toString() => super.toString();
}
